---
driver:
  name: docker
  hostname: nomad-formula.ci.local
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  # No need for chef as we're not using busser
  require_chef: false
  formula: nomad
  dependencies:
    - name: golang
      path: test/dependencies/golang-formula
  pillars-from-files:
    nomad.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - nomad
  state_top:
    base:
      '*':
        - nomad

platforms:
  - name: debian-8
    driver_config:
      # This particular driver config is required to make sure that
      # systemd is running inside the container.
      run_command: /sbin/init

suites:
  - name: nomad-install
  # This one should be tested locally as it times out on Travis CI
  # - name: nomad-install_build
  #   provisioner:
  #     state_top:
  #       base:
  #         '*':
  #           - golang
  #           - nomad
  #     pillars:
  #       top.sls:
  #         base:
  #           '*':
  #             - golang
  #             - nomad
  #             - nomad-build
  #       nomad-build.sls:
  #           nomad:
  #             build: true
  #       golang.sls:
  #           golang:
  #             lookup:
  #               version: 1.7.5
  - name: nomad-config
  - name: nomad-uninstall
    provisioner:
      state_top:
        base:
          '*':
            - nomad
            - nomad.uninstall

verifier:
  name: shell
  remote_exec: false
  # Command changed to allow running the same tests with different parameters
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$(echo $KITCHEN_SUITE | sed 's/_.*//')
  